name: Lighthouse CI
on:
  pull_request:
    branches: [main]
jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: List files for debugging
        run: ls -alh

      - name: Install dependencies
        run: yarn

      - name: Start server
        run: yarn start &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Lighthouse mobile audit
        run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Lighthouse desktop audit
        run: yarn lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Stop server
        run: kill $(jobs -p)
