name: Lighthouse CI

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Start HTTP Server
        run: npx http-server ./dist -p 4173 &
        shell: bash

      - name: Wait for HTTP Server to start
        run: sleep 10

      - name: Run Lighthouse CI
        run: lhci autorun --config=.lighthouserc.js

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-results
          path: .lighthouseci

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Lighthouse CI results: See details in the Actions tab. Accessibility Score must be 100. Review the artifacts for detailed reports.
          token: ${{ secrets.GITHUB_TOKEN }}
